server:
  port: 3002

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:

      - id: user-service
        uri: http://localhost:3000
        predicates:
          - Path=/api/users/**

      - id: auth-service
        uri: http://localhost:3001
        predicates:
          - Path=/api/auth/**

      - id: product-service
        uri: http://localhost:3003
        predicates:
          - Path=/api/product/**

      - id: order-service
        uri: http://localhost:3004
        predicates:
          - Path=/api/order/**

      - id: order-service
        uri: http://localhost:3004
        predicates:
          - Path=/api/coupon/**

jwt:
  secret: 9fKx3LqP7mZtR2vX8nBcY5wHsU4jQa1eTf6GdWp0rTy9UiOlVk3Nz7MhSe2AxCd
