server:
  port: 3000

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/userServiceDb
    username: postgres
    password: somu
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
