server:
  port: 3004

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orderServiceDb
    username: postgres
    password: somu
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379