server:
  port: 3003

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/productServiceDb
    username: postgres
    password: somu
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true

  metrics:
    tags:
      application: ${spring.application.name}