server:
  port: 3005

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5432/inventoryServiceDb
    username: postgres
    password: somu
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
      bootstrap-servers: localhost:9092
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        properties:
          spring.json.add.type.headers: false   # ← producer does NOT add type headers

      consumer:
        group-id: flash-order-v2
        auto-offset-reset: earliest
        enable-auto-commit: false               # ← required for manual ack
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted.packages: "com.flashdrop.inventoryService.*"
          spring.json.value.default.type: "com.flashdrop.inventoryService.dto.KafkaContext"  # ← ADD THIS
          spring.json.use.type.headers: false   # ← ADD THIS

      listener:
        ack-mode: MANUAL_IMMEDIATE

logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka: WARN

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true

  metrics:
    tags:
      application: ${spring.application.name}